fragment FragmentParagraphInterface on ParagraphInterface {
  __typename
  id
  behaviors
  status
}

fragment FragmentParagraphStanfordAccordion on ParagraphStanfordAccordion {
  ...FragmentParagraphInterface
  suAccordionBody {
    ...FragmentText
  }
  suAccordionTitle
}

fragment FragmentParagraphStanfordBanner on ParagraphStanfordBanner {
  ...FragmentParagraphInterface
  suBannerHeader
  suBannerBody {
    ...FragmentText
  }
  suBannerSupHeader
  suBannerButton {
    url
    title
  }
  suBannerImage {
    ...FragmentMediaImage
  }
}

fragment FragmentParagraphStanfordCard on ParagraphStanfordCard {
  ...FragmentParagraphInterface
  suCardHeader
  suCardSuperHeader
  suCardBody {
    ...FragmentText
  }
  suCardLink {
    url
    title
  }
  suCardMedia {
    ...FragmentMediaUnion
  }
}

fragment FragmentParagraphStanfordEntity on ParagraphStanfordEntity {
  ...FragmentParagraphInterface
  suEntityHeadline
  suEntityDescription {
    ...FragmentText
  }
  suEntityButton {
    url
    title
  }
  suEntityItem {
    ... on NodeInterface {
      id
      path
    }
  }
}

fragment FragmentParagraphStanfordGallery on ParagraphStanfordGallery {
  ...FragmentParagraphInterface
  suGalleryHeadline
  suGalleryDescription {
    ...FragmentText
  }
  suGalleryButton {
    url
    title
  }
  suGalleryImages {
    ...FragmentMediaStanfordGalleryImage
  }
}

fragment FragmentParagraphStanfordList on ParagraphStanfordList {
  ...FragmentParagraphInterface
  suListHeadline
  suListDescription {
    ...FragmentText
  }
  suListButton {
    url
    title
  }
  suListView {
    view
    display
    contextualFilter
    pageSize
  }
}

fragment FragmentParagraphStanfordMediaCaption on ParagraphStanfordMediaCaption {
  ...FragmentParagraphInterface
  suMediaCaptionMedia {
    ...FragmentMediaUnion
  }
  suMediaCaptionLink {
    url
    title
  }
  suMediaCaptionCaption {
    ...FragmentText
  }
}

fragment FragmentParagraphStanfordPersonCtum on ParagraphStanfordPersonCtum {
  ...FragmentParagraphInterface
  suPersonCtaName
  suPersonCtaTitle
  suPersonCtaLink {
    url
    title
  }
  suPersonCtaImage {
    ...FragmentMediaImage
  }
}

fragment FragmentParagraphStanfordSchedule on ParagraphStanfordSchedule {
  ...FragmentParagraphInterface
  suScheduleHeadline
  suScheduleDescription {
    ...FragmentText
  }
  suScheduleDateTime {
    ...FragmentSmartDateType
  }
  suScheduleLocation {
    ...FragmentAddressType
  }
  suScheduleUrl {
    url
    title
  }
  suScheduleSpeaker {
    ...FragmentParagraphStanfordPersonCtum
  }
}

fragment FragmentParagraphStanfordLayout on ParagraphStanfordLayout {
  ...FragmentParagraphInterface
}

fragment FragmentParagraphStanfordSpacer on ParagraphStanfordSpacer {
  ...FragmentParagraphInterface
  suSpacerSize
}

fragment FragmentParagraphStanfordWysiwyg on ParagraphStanfordWysiwyg {
  ...FragmentParagraphInterface
  suWysiwygText {
    ...FragmentText
  }
}

fragment FragmentParagraphStanfordPageTitleBanner on ParagraphStanfordPageTitleBanner {
  ...FragmentParagraphInterface
  suTitleBannerImage {
    ...FragmentMediaImage
  }
}

fragment FragmentParagraphSumCalculator on ParagraphSumCalculator {
  ...FragmentParagraphInterface
  sumCalcAppFee
  sumCalcBooks
  sumCalcCommuteHelp {
    ...FragmentText
  }
  sumCalcDocuments
  sumCalcGradAppHelp {
    ...FragmentText
  }
  sumCalcGradUnitCost {
    ...FragmentDoubleIntFloat
  }
  sumCalcGradUnitHelp {
    ...FragmentText
  }
  sumCalcHealthFee
  sumCalcHighAppHelp {
    ...FragmentText
  }
  sumCalcHighUnitCost {
    ...FragmentDoubleIntFloat
  }
  sumCalcHighUnitHelp {
    ...FragmentText
  }
  sumCalcHouseFees {
    ...FragmentDoubleStringFloat
  }
  sumCalcHouseHelp {
    ...FragmentText
  }
  sumCalcI20Fee
  sumCalcI20Help {
    ...FragmentText
  }
  sumCalcInsHelp {
    ...FragmentText
  }
  sumCalcInsWaveHelp {
    ...FragmentText
  }
  sumCalcInsurance
  sumCalcMailFee
  sumCalcMeals
  sumCalcProgFee {
    ...FragmentDoubleStringFloat
  }
  sumCalcTechFee
  sumCalcUgAppHelp {
    ...FragmentText
  }
  sumCalcUgUnitCost {
    ...FragmentDoubleIntFloat
  }
  sumCalcUgUnitHelp {
    ...FragmentText
  }
}

fragment FragmentParagraphSumAccordion on ParagraphSumAccordion {
  ...FragmentParagraphInterface
  sumAccordionsAccords {
    ...FragmentParagraphStanfordAccordion
  }
  sumAccordionsDesc {
    ...FragmentText
  }
  sumAccordionsHeading
}

fragment FragmentParagraphSumArcBanner on ParagraphSumArcBanner {
  ...FragmentParagraphInterface
  sumArcSuperhead
  sumArcImage {
    ...FragmentMediaImage
  }
  sumArcDescription {
    ...FragmentText
  }
}

fragment FragmentParagraphSumCarousel on ParagraphSumCarousel {
  ...FragmentParagraphInterface
  sumCarouselDescription {
    ...FragmentText
  }
  sumCarouselHeader
  sumCarouselLink {
    ...FragmentLink
  }
  sumCarouselSlides {
    ...FragmentParagraphStanfordCard
    ...FragmentParagraphSumSlideTeaser
  }
  sumCarouselSuperheader
}

fragment FragmentParagraphSumSlideTeaser on ParagraphSumSlideTeaser {
  ...FragmentParagraphInterface
  sumSlideTeaserEntity {
    ...FragmentNodeTeaserUnion
  }
}

fragment FragmentParagraphSumTopBanner on ParagraphSumTopBanner {
  ...FragmentParagraphInterface
  sumTopBannerCards {
    ...FragmentParagraphStanfordCard
  }
  sumTopBannerDescrip {
    ...FragmentText
  }
  sumTopBannerImage {
    ...FragmentMediaImage
  }
  sumTopBannerLink {
    ...FragmentLink
  }
  sumTopBannerSuperhead
}

fragment FragmentParagraphSumVideo on ParagraphSumVideo {
  ...FragmentParagraphInterface
  sumVideoVideo {
    ...FragmentMediaVideo
  }
}

fragment FragmentParagraphSumUserFavorite on ParagraphSumUserFavorite {
  ...FragmentParagraphInterface
}

fragment FragmentParagraphSumCourseFilter on ParagraphSumCourseFilter {
  ...FragmentParagraphInterface
}

fragment FragmentParagraphSumFact on ParagraphSumFact {
  ...FragmentParagraphInterface
  sumFactsLabel
  sumFactsText
}

fragment FragmentParagraphSumAtAGlance on ParagraphSumAtAGlance {
  ...FragmentParagraphInterface
  sumAtAGlanceDescrip {
    ...FragmentText
  }
  sumAtAGlanceFacts {
    ...FragmentParagraphSumFact
  }
  sumAtAGlanceHeadline
  sumAtAGlanceLink {
    ...FragmentLink
  }
}

fragment FragmentParagraphSumPillBanner on ParagraphSumPillBanner {
  ...FragmentParagraphInterface
  sumPillBannerBkgd {
    ... FragmentMediaImage
  }
  sumPillBannerCards {
    ... FragmentParagraphStanfordCard
  }
  sumPillBannerDescrip {
    ... FragmentText
  }
  sumPillBannerHeadline
  sumPillBannerLink {
    ... FragmentLink
  }
  sumPillBannerSuphead
}

fragment FragmentParagraphSumTestimonial on ParagraphSumTestimonial {
  ...FragmentParagraphInterface
  sumTestimonialAffi
  sumTestimonialBkgImg {
    ...FragmentMediaImage
  }
  sumTestimonialButton {
    ...FragmentLink
  }
  sumTestimonialDescrip {
    ...FragmentText
  }
  sumTestimonialHeading
  sumTestimonialHsVideo {
    ...FragmentMediaImage
    ...FragmentMediaVideo
  }
  sumTestimonialName
  sumTestimonialType
  sumTestimonialUniv
}

fragment FragmentParagraphUnion on ParagraphUnion {
  ...FragmentParagraphInterface
  ...FragmentParagraphStanfordAccordion
  ...FragmentParagraphStanfordBanner
  ...FragmentParagraphStanfordCard
  ...FragmentParagraphStanfordEntity
  ...FragmentParagraphStanfordGallery
  ...FragmentParagraphStanfordLayout
  ...FragmentParagraphStanfordList
  ...FragmentParagraphStanfordMediaCaption
  ...FragmentParagraphStanfordSpacer
  ...FragmentParagraphStanfordWysiwyg
  ...FragmentParagraphSumAccordion
  ...FragmentParagraphSumArcBanner
  ...FragmentParagraphSumCalculator
  ...FragmentParagraphSumCarousel
  ...FragmentParagraphSumCourseFilter
  ...FragmentParagraphSumTopBanner
  ...FragmentParagraphSumUserFavorite
  ...FragmentParagraphSumVideo
  ...FragmentParagraphSumAtAGlance
  ...FragmentParagraphSumPillBanner
  ...FragmentParagraphSumTestimonial
}
