
fragment FragmentParagraphInterface on ParagraphInterface {
    __typename
    id
    behaviors
}

fragment FragmentParagraphStanfordAccordion on ParagraphStanfordAccordion {
    ...FragmentParagraphInterface
    suAccordionBody {
        processed
    }
    suAccordionTitle
}

fragment FragmentParagraphStanfordBanner on ParagraphStanfordBanner {
    ...FragmentParagraphInterface
    suBannerHeader
    suBannerBody {
        processed
    }
    suBannerSupHeader
    suBannerButton {
        url
        title
    }
    suBannerImage {
        ...FragmentMediaImage
    }
}

fragment FragmentParagraphStanfordCard on ParagraphStanfordCard {
    ...FragmentParagraphInterface
    suCardHeader
    suCardSuperHeader
    suCardBody {
        processed
    }
    suCardLink {
        url
        title
    }
    suCardMedia {
        ...FragmentMediaUnion
    }
}

fragment FragmentParagraphStanfordEntity on ParagraphStanfordEntity {
    ...FragmentParagraphInterface
    suEntityHeadline
    suEntityDescription {
        processed
    }
    suEntityButton {
        url
        title
    }
    suEntityItem {
        ... on NodeInterface {
            id
            path
        }
    }
}

fragment FragmentParagraphStanfordGallery on ParagraphStanfordGallery {
    ...FragmentParagraphInterface
    suGalleryHeadline
    suGalleryDescription {
        processed
    }
    suGalleryButton {
        url
        title
    }
    suGalleryImages {
        ...FragmentMediaStanfordGalleryImage
    }
}

fragment FragmentParagraphStanfordList on ParagraphStanfordList {
    ...FragmentParagraphInterface
    suListHeadline
    suListDescription {
        processed
    }
    suListButton {
        url
        title
    }
    suListView {
        view
        display
        contextualFilter
        pageSize
    }
}

fragment FragmentParagraphStanfordMediaCaption on ParagraphStanfordMediaCaption {
    ...FragmentParagraphInterface
    suMediaCaptionMedia {
        ...FragmentMediaUnion
    }
    suMediaCaptionLink {
        url
        title
    }
    suMediaCaptionCaption {
        processed
    }
}

fragment FragmentParagraphStanfordPersonCtum on ParagraphStanfordPersonCtum {
    ...FragmentParagraphInterface
    suPersonCtaName
    suPersonCtaTitle
    suPersonCtaLink {
        url
        title
    }
    suPersonCtaImage {
        ...FragmentMediaImage
    }
}

fragment FragmentParagraphStanfordSchedule on ParagraphStanfordSchedule {
    ...FragmentParagraphInterface
    suScheduleHeadline
    suScheduleDescription {
        processed
    }
    suScheduleDateTime {
        ...FragmentSmartDateType
    }
    suScheduleLocation {
        ...FragmentAddressType
    }
    suScheduleUrl {
        url
        title
    }
    suScheduleSpeaker {
        ...FragmentParagraphStanfordPersonCtum
    }
}

fragment FragmentParagraphStanfordLayout on ParagraphStanfordLayout {
    ...FragmentParagraphInterface
}

fragment FragmentParagraphStanfordSpacer on ParagraphStanfordSpacer {
    ...FragmentParagraphInterface
    suSpacerSize
}

fragment FragmentParagraphStanfordWysiwyg on ParagraphStanfordWysiwyg {
    ...FragmentParagraphInterface
    suWysiwygText {
        processed
    }
}

fragment FragmentParagraphStanfordPageTitleBanner on ParagraphStanfordPageTitleBanner {
    ...FragmentParagraphInterface
    suTitleBannerImage {
        ...FragmentMediaImage
    }
}

fragment FragmentParagraphSumCalculator on ParagraphSumCalculator {
    ...FragmentParagraphInterface
    sumCalcAppFee
    sumCalcBooks
    sumCalcCommuteHelp {
        processed
    }
    sumCalcDocuments
    sumCalcGradAppHelp {
        processed
    }
    sumCalcGradUnitCost {
        ...FragmentDoubleIntFloat
    }
    sumCalcGradUnitHelp {
        processed
    }
    sumCalcHealthFee
    sumCalcHighAppHelp {
        processed
    }
    sumCalcHighUnitCost {
        ...FragmentDoubleIntFloat
    }
    sumCalcHighUnitHelp {
        processed
    }
    sumCalcHouseFees {
        ...FragmentDoubleStringFloat
    }
    sumCalcHouseHelp {
        processed
    }
    sumCalcI20Fee
    sumCalcI20Help {
        processed
    }
    sumCalcInsHelp {
        processed
    }
    sumCalcInsWaveHelp {
        processed
    }
    sumCalcInsurance
    sumCalcMailFee
    sumCalcMeals
    sumCalcProgFee {
        ...FragmentDoubleStringFloat
    }
    sumCalcTechFee
    sumCalcUgAppHelp {
        processed
    }
    sumCalcUgUnitCost {
        ...FragmentDoubleIntFloat
    }
    sumCalcUgUnitHelp {
        processed
    }
}

fragment FragmentParagraphSumAccordion on ParagraphSumAccordion {
    ...FragmentParagraphInterface
    sumAccordionsAccords {
        ...FragmentParagraphStanfordAccordion
    }
    sumAccordionsDesc {
        processed
    }
    sumAccordionsHeading
}

fragment FragmentParagraphSumArcBanner on ParagraphSumArcBanner {
    ...FragmentParagraphInterface
    sumArcHeadline
    sumArcSuperhead
    sumArcImage {
        ...FragmentMediaImage
    }
    sumArcDescription {
        processed
    }
}

fragment FragmentParagraphUnion on ParagraphUnion {
    ...FragmentParagraphInterface
    ...FragmentParagraphStanfordAccordion
    ...FragmentParagraphStanfordBanner
    ...FragmentParagraphStanfordCard
    ...FragmentParagraphStanfordEntity
    ...FragmentParagraphStanfordGallery
    ...FragmentParagraphStanfordList
    ...FragmentParagraphStanfordMediaCaption
    ...FragmentParagraphStanfordSpacer
    ...FragmentParagraphStanfordWysiwyg
    ...FragmentParagraphStanfordLayout
    ...FragmentParagraphSumCalculator
    ...FragmentParagraphSumAccordion
    ...FragmentParagraphSumArcBanner
}
