
name: Build & Lint
on: [push]
jobs:
  lint:
    name: Lint & TS Check
    runs-on: ubuntu-latest
    container:
      image: node:20
      env:
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${{ secrets.NEXT_PUBLIC_DRUPAL_BASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          yarn
          yarn lint
      - name: Build
        run: |
          yarn build